name: Backend CI/CD

on:
  push:
    branches:
      - main  # Ejecuta en cada push a la rama principal
  pull_request:

jobs:
  lint-test:
    name: Lint & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
        

      - name: Run Ruff (Lint)
        run: |
          pip install ruff
          ruff check . --fix


      - name: Run Pytest (Tests)
        run: |
          coverage run -m pytest back-calculadora/tests -v -s

      - name: Generate Coverage Report
        run: |  
          coverage report -m --omit="/usr/*"


  dockerhub:
    name: Build & Push to DockerHub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/back-calculadora:latest .

      - name: Push Docker Image to DockerHub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/back-calculadora:latest

  ghcr:
    name: Build & Push to GHCR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository 
        uses: actions/checkout@v3

      - name: Log in to GHCR
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker Image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/back-calculadora:latest .

      - name: Push Docker Image to GHCR
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/back-calculadora:latest
