name: Backend CI/CD

on:
  push:
    branches:
      - main  # Ejecuta en cada push a la rama principal

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  lint-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
        

      - name: Run Ruff (Lint)
        run: |
          pip install ruff
          ruff check . --fix


      - name: Run Pytest (Tests)
        run: |
          pip install httpx
          coverage run -m pytest tests/ -v -s

      - name: Generate Coverage Report
        run: |  
          coverage report -m --omit="/usr/*"


  dockerhub:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t ${{ vars.DOCKER_USERNAME }}/back-calculadora:latest .

      - name: Push Docker Image to DockerHub
        run: |
          docker push ${{ vars.DOCKER_USERNAME }}/back-calculadora:latest

  ghcr:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout repository 
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
            registry: ${{ env.REGISTRY }}
            username: ${{ github.actor }}
            password: ${{ secrets.CD_TOKEN}}

      - name: Build Docker Image
        run:
          docker build . --tag ghcr.io/david-drz/back-calculator:latest

      - name: Push Docker image
        run:
          docker push ghcr.io/david-drz/back-calculator:latest
